name: Accessibility Testing

on:
  push:
    branches: [clean-main]
    paths:
      - 'components/**'
      - 'screens/**'
      - '__tests__/accessibility/**'

jobs:
  accessibility-tests:
    name: Run Accessibility Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Check for accessibility tests
        run: |
          if [ -d "__tests__/accessibility" ] && [ "$(ls -A __tests__/accessibility 2>/dev/null)" ]; then
            echo "✅ Accessibility tests found"
            npm test -- --testPathPattern=__tests__/accessibility --passWithNoTests
          else
            echo "⚠️ No accessibility tests found, skipping..."
            exit 0
          fi