name: Accessibility Testing

on:
  push:
    branches: [main, develop]
    paths:
      - 'components/**'
      - 'screens/**'
      - 'styles/**'
      - 'atomic/**'
      - 'constants/Colors.ts'
      - 'contexts/ThemeContext.tsx'
  pull_request:
    branches: [main, develop]
    paths:
      - 'components/**'
      - 'screens/**'
      - 'styles/**'
      - 'atomic/**'
      - 'constants/Colors.ts'
      - 'contexts/ThemeContext.tsx'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  accessibility-tests:
    name: Run Accessibility Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Jest dependencies
        run: bash scripts/install-jest-dependencies.sh

      - name: Run Jest tests for accessibility components
        run: npm test -- --testPathPattern=__tests__/accessibility

      - name: Run color contrast tests
        run: node scripts/run-color-contrast-tests.js

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: accessibility-test-results
          path: |
            test-results
            coverage
            accessibility-report.json

  # Add a job to check for accessibility issues in the UI
  axe-test:
    name: Run Axe Accessibility Tests
    runs-on: ubuntu-latest
    needs: accessibility-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer
        run: npm install --save-dev puppeteer @axe-core/puppeteer

      - name: Start web server
        run: npm run web & npx wait-on http://localhost:19006

      - name: Run Axe accessibility tests
        run: node scripts/run-axe-tests.js

      - name: Upload axe results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: axe-test-results
          path: axe-results.json
