name: Auto Deploy to GoDaddy

on:
  push:
    branches:
      - main
      - clean-main
    paths:
      - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /public_html/

      - name: Notify on success
        if: success()
        run: |
          echo "::notice::🚀 Successfully deployed to GoDaddy"

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::❌ Deployment to GoDaddy failed"
