name: Build and Test

on:
  push:
    branches:
      - clean-main
    paths:
      - 'src/**'
      - 'components/**'
      - 'screens/**'
      - 'services/**'
      - 'utils/**'
      - 'package.json'
      - '__tests__/**'
  pull_request:
    branches:
      - clean-main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true
        
      - name: Auto-fix lint issues
        run: npm run lint -- --fix
        continue-on-error: true
        
      - name: Run type checking
        run: |
          if npm run | grep -q "typecheck"; then
            npm run typecheck
          else
            echo "No typecheck script found, skipping..."
          fi
        continue-on-error: true
        
      - name: Run tests
        run: |
          if npm run | grep -q "test"; then
            npm test -- --coverage --watchAll=false
          else
            echo "No test script found, skipping..."
          fi
        continue-on-error: true
        
      - name: Build project
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found, skipping..."
          fi
        continue-on-error: true
        
      - name: Commit lint fixes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No lint fixes to commit"
          else
            git commit -m "🔧 Auto-fix lint issues

            - Applied ESLint auto-fixes
            - Automated via GitHub Actions"
            git push
          fi