name: Code Analysis

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:     # Allow manual triggering
  push:
    branches: [ main ]   # Run on push to main branch
    paths:
      - 'src/**'         # Only run when source code changes
      - 'functions/**'
      - 'scripts/**'

jobs:
  analyze:
    name: Run Code Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for historical analysis
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create directory structure
        run: |
          mkdir -p .roocode/checkpoints/completed
          mkdir -p .roocode/checkpoints/corrupted
          mkdir -p .roocode/logs
          mkdir -p reports/complete-analysis
      
      - name: Run Complete Analysis
        run: |
          node scripts/roo-complete-analysis.js analyze \
            --timeframe "1 month ago" \
            --output-dir ./reports/complete-analysis
      
      - name: Upload Analysis Reports
        uses: actions/upload-artifact@v3
        with:
          name: analysis-reports
          path: reports/complete-analysis/
      
      - name: Generate Summary
        id: summary
        run: |
          echo "## Code Analysis Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f reports/complete-analysis/complete-analysis-data.json ]; then
            DUPLICATE_GROUPS=$(jq -r '.duplicates.groups // 0' reports/complete-analysis/complete-analysis-data.json)
            COMMITS=$(jq -r '.history.commits // 0' reports/complete-analysis/complete-analysis-data.json)
            FEATURES=$(jq -r '.history.features // 0' reports/complete-analysis/complete-analysis-data.json)
            CONTRIBUTORS=$(jq -r '.history.contributors // 0' reports/complete-analysis/complete-analysis-data.json)
            
            echo "### Summary" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Duplicate Groups:** ${DUPLICATE_GROUPS}" >> $GITHUB_STEP_SUMMARY
            echo "- **Commits Analyzed:** ${COMMITS}" >> $GITHUB_STEP_SUMMARY
            echo "- **Features Tracked:** ${FEATURES}" >> $GITHUB_STEP_SUMMARY
            echo "- **Contributors:** ${CONTRIBUTORS}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Reports" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- [Complete Analysis Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Analysis failed to generate reports" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '❌ Code Analysis Failed',
              body: `The code analysis workflow failed on ${context.sha}.\n\nSee: https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })

  cleanup:
    name: Clean up old operations
    runs-on: ubuntu-latest
    needs: analyze
    if: always()  # Run even if analyze job fails
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Clean up old operations
        run: |
          node scripts/roo-duplicates.js clean --older-than 30
          node scripts/roo-history-analyze.js clean --older-than 30
          node scripts/roo-complete-analysis.js clean --older-than 30