name: Daily Health Check

on:
  schedule:
    # Run at 5:00 AM UTC (1:00 AM EDT) every day
    - cron: '0 5 * * *'
  push:
    branches:
      - clean-main
    paths:
      - 'public/**'
      - 'src/**'
      - 'package.json'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Puppeteer
        run: npm install --save-dev puppeteer --legacy-peer-deps

      - name: Run health check
        id: health_check
        run: |
          chmod +x ./scripts/verify-deployment-health.sh
          ./scripts/verify-deployment-health.sh
          echo "REPORT_PATH=$(ls -t ./health-report/*.txt | head -1)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
          
          # Check if any failures in the report
          if grep -q "❌" ./health-report/*.txt; then
            echo "HEALTH_STATUS=failure" >> $GITHUB_ENV
          else
            echo "HEALTH_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Upload health report
        uses: actions/upload-artifact@v3
        with:
          name: health-report-${{ env.TIMESTAMP }}
          path: ./health-report/
          retention-days: 30

      - name: Send email notification on failure
        if: env.HEALTH_STATUS == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "⚠️ AI Sports Edge - Health Check Failed"
          body: |
            The daily health check for AI Sports Edge has detected issues.
            
            Date: ${{ env.TIMESTAMP }}
            
            Please check the attached health report for details.
            
            View the GitHub Actions run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: AI Sports Edge Health Monitor
          attachments: ${{ env.REPORT_PATH }}

      - name: Send Slack notification on failure
        if: env.HEALTH_STATUS == 'failure'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⚠️ AI Sports Edge - Health Check Failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "⚠️ AI Sports Edge - Health Check Failed"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The daily health check for AI Sports Edge has detected issues.\n\nDate: ${{ env.TIMESTAMP }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "View the <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Actions run> for details."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK