name: Firebase Deploy

on:
  push:
    branches: [clean-main]
    paths:
      - 'public/**'
      - 'firebase.json'
      - '.firebaserc'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify files exist
        run: |
          echo "🔍 Checking required files..."
          ls -la public/
          [ -f "public/index.html" ] && echo "✅ index.html found" || echo "❌ index.html missing"
          [ -f "public/styles.css" ] && echo "✅ styles.css found" || echo "❌ styles.css missing"
          [ -f "firebase.json" ] && echo "✅ firebase.json found" || echo "❌ firebase.json missing"
          
      - name: Verify neon theme in CSS
        run: |
          echo "🎨 Checking for neon theme..."
          if grep -q "#00F0FF" public/styles.css; then
            echo "✅ Neon theme (#00F0FF) found in styles.css"
          else
            echo "❌ Neon theme not found in styles.css"
            echo "Current CSS colors:"
            grep -A 3 ":root" public/styles.css | head -5
          fi
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_SPORTS_EDGE }}'
          projectId: ai-sports-edge
          channelId: live