name: Firebase Deploy

on:
  push:
    branches: [clean-main]
    paths:
      - 'public/**'
      - 'functions/**'
      - 'firebase.json'

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Prepare public directory
        run: |
          mkdir -p public
          if [ ! -f "public/index.html" ]; then
            cp public/index.html public/index.html.bak 2>/dev/null || true
            echo "✅ Public directory ready"
          fi
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_SPORTS_EDGE }}'
          projectId: ai-sports-edge
          channelId: live