name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Prepare dist directory
        run: |
          # Ensure dist directory exists
          mkdir -p dist
          
          # Only copy from public if dist is empty
          if [ -z "$(ls -A dist 2>/dev/null)" ]; then
            if [ -d "public" ]; then
              cp -r public/* dist/ 2>/dev/null || echo "No files to copy from public"
            fi
          fi
          
          # Make sure there's at least an index.html file
          if [ ! -f "dist/index.html" ]; then
            echo "<html><body><h1>AI Sports Edge</h1><p>Coming Soon</p></body></html>" > dist/index.html
          fi
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ai-sports-edge
          target: aisportsedge-app
