name: Firebase Deploy

on:
  push:
    branches: [clean-main]
    paths:
      - 'public/**'
      - 'functions/**'
      - 'firebase.json'

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Prepare public directory
        run: |
          mkdir -p public
          if [ ! -f "public/index.html" ]; then
            cp public/index.html public/index.html.bak 2>/dev/null || true
            echo "✅ Public directory ready"
          fi
          
      - name: Deploy to Firebase
        run: |
          if command -v firebase &> /dev/null; then
            firebase deploy --only hosting
          else
            echo "⚠️ Firebase CLI not available, skipping deploy"
          fi