name: Firebase Deploy

on:
  push:
    branches: [clean-main]
    paths:
      - 'public/**'
      - 'firebase.json'
      - '.firebaserc'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify files exist
        run: |
          echo "🔍 Checking required files..."
          ls -la public/
          [ -f "public/index.html" ] && echo "✅ index.html found" || echo "❌ index.html missing"
          [ -f "public/styles.css" ] && echo "✅ styles.css found" || echo "❌ styles.css missing"
          [ -f "firebase.json" ] && echo "✅ firebase.json found" || echo "❌ firebase.json missing"
          
      - name: Verify neon theme in CSS
        run: |
          echo "🎨 Checking for neon theme..."
          if grep -q "#00F0FF" public/styles.css; then
            echo "✅ Neon theme (#00F0FF) found in styles.css"
          else
            echo "❌ Neon theme not found in styles.css"
            echo "Current CSS colors:"
            grep -A 3 ":root" public/styles.css | head -5
          fi
          
      - name: Deploy to Firebase (Method 1)
        uses: FirebaseExtended/action-hosting-deploy@v0
        continue-on-error: true
        id: firebase_deploy_1
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_SPORTS_EDGE }}'
          projectId: ai-sports-edge
          
      - name: Setup Node.js (Fallback)
        if: steps.firebase_deploy_1.outcome == 'failure'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Firebase CLI (Fallback)
        if: steps.firebase_deploy_1.outcome == 'failure'
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase (Method 2)
        if: steps.firebase_deploy_1.outcome == 'failure'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "🚀 Deploying to Firebase using CLI..."
          firebase use ai-sports-edge --token "$FIREBASE_TOKEN"
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"